name: Clone Test Database
run-name: Create test database to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy'
          required: true
          default: 'backup'
          type: 'choice'
          options:
            - aa
            - acadia
            - ad
            - backup
            - bob
            - dg
            - el
            - es
            - glacier
            - hotgov
            - kma
            - litterbox
            - meoward
            - nl
            - olympic
            - potato
            - my
            - product
            - rh
            - yellowstone
            - zion
jobs:
  clone-database:
    runs-on: ubuntu-24.04
    steps:
        - name: Check secret length
          env:
            # must be the github secrets for the receiving sandbox
            CF_USERNAME: ${{ github.event.inputs.environment }}_USERNAME
            DESTINATION_ENVIRONMENT: ${{ github.event.inputs.environment}}
            SOURCE_ENVIRONMENT: testdb
          with:
            cf_username: ${{secrets[env.CF_USERNAME]}}
          run: |
            echo "CF is set (length: ${#cf_username})"
            echo "${{secrets.CF_USERNAME}}"