name: Clone Test Database
run-name: Create test database to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy'
          required: true
          default: 'backup'
          type: 'choice'
          options:
            - aa
            - acadia
            - ad
            - backup
            - bob
            - dg
            - el
            - es
            - glacier
            - hotgov
            - kma
            - litterbox
            - meoward
            - nl
            - olympic
            - potato
            - my
            - product
            - rh
            - yellowstone
            - zion
jobs:
  clone-database:
    runs-on: ubuntu-24.04
    with:
      # must be the github secrets for the receiving sandbox
      CF_USERNAME: CF_${{ github.event.inputs.environment }}_USERNAME
      CF_PASSWORD: CF_${{ github.event.inputs.environment }}_PASSWORD
      DESTINATION_ENVIRONMENT: ${{ github.event.inputs.environment}}
      SOURCE_ENVIRONMENT: testdb
    steps:
        - name: Clone Database
          env:
            cf_username: ${{ secrets[env.CF_USERNAME] }}
            cf_password: ${{ secrets[env.CF_PASSWORD] }}
          run: 
            echo "CF is set (length: ${#cf_username})"
            
        - name: Cleanup
          if: always()
          run: cf unshare-service getgov-$DESTINATION_ENVIRONMENT-database -s $SOURCE_ENVIRONMENT -f
