name: Clone Test Database
run-name: Create test database to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy'
          required: true
          default: 'backup'
          type: 'choice'
          options:
            - aa
            - acadia
            - ad
            - backup
            - bob
            - dg
            - el
            - es
            - glacier
            - hotgov
            - kma
            - litterbox
            - meoward
            - nl
            - olympic
            - potato
            - my
            - product
            - rh
            - yellowstone
            - zion
jobs:
  clone-database:
    runs-on: ubuntu-24.04
    steps:
        - name: Install dependencies
          run: |
            # install cf cli and other tools
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
            echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list

            sudo apt-get update
            sudo apt-get install cf8-cli
            
            # install cg-manage-rds tool
            pip install git+https://github.com/cloud-gov/cg-manage-rds.git
        
        - name: Check secret length
          env:
            # must be the github secrets for the receiving sandbox
            CF_MY_USERNAME: ${{secrets.MY_USERNAME}}
            CF_AD_USERNAME: ${{secrets.AD_USERNAME}}
            DESTINATION_ENVIRONMENT: ${{ github.event.inputs.environment}}
            SOURCE_ENVIRONMENT: testdb
          run: |
            #Convert environment to uppercase for variable name construction
            env_upper=$(echo "$DESTINATION_ENVIRONMENT" | tr '[:lower:]' '[:upper:]')
            username="CF_${env_upper}_USERNAME"
            echo "CF USERNAME is set (length: ${#username})"
